export default {
  FETCH_PROMOTED: 'FETCH_PROMOTED',
  FETCH_UPCOMING: 'FETCH_UPCOMING',
  FETCH_POPULAR: 'FETCH_POPULAR',
  FETCH_TOPRATED: 'FETCH_TOPRATED',
  FETCH_MOVIE: 'FETCH_MOVIE',
  CLEAR_PAGE: 'CLEAR_PAGE',
  FETCH_CAST: 'FETCH_CAST',
  FETCH_SEARCH: 'FETCH_SEARCH',
  FETCH_ERROR: 'FETCH_ERROR'
}
